// Generated by web/scripts/gen-deployment-facts.mjs. Do not edit.
//
// Sourced from deployments/*.json so the landing page can state what is
// deployed without making a request. `prebuild` re-runs the generator with
// --check, so a redeploy that is not reflected here fails the build.

export type DeployedProgram = {
  key: string;
  label: string;
  purpose: string;
  address: string;
};

export type DeploymentFacts = {
  cluster: string;
  ready: boolean;
  updatedAt: string | null;
  genesisHash: string | null;
  quoteMint: string | null;
  programs: DeployedProgram[];
  magicblock: {
    validator: string | null;
    registeredBooks: number;
    trading: string | null;
    settlementExit: string | null;
  };
};

export const DEPLOYMENTS: Record<string, DeploymentFacts> = {
  "devnet": {
    "cluster": "devnet",
    "ready": true,
    "updatedAt": "2026-08-22T00:00:00Z",
    "genesisHash": "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG",
    "quoteMint": "HF8CvJ8afuhvRDiwujtaxH6X863sJNrAtzhAty51sDAa",
    "programs": [
      {
        "key": "series",
        "label": "Series",
        "purpose": "Splits collateral into P and N, and settles them",
        "address": "AJPJRQQpgT461SaiBvZY4ixdS6S5R2QYQsod6Qdpm8p9"
      },
      {
        "key": "factory",
        "label": "Factory",
        "purpose": "The registry that makes a series canonical",
        "address": "CRBW3Et1ogjExdSnFty3gM4zyGoN7He5zfqkaieZqQkZ"
      },
      {
        "key": "market",
        "label": "Market",
        "purpose": "The order book",
        "address": "FYAhsmE2JCxuAFhq2asH2wC4i7ZaUE7kwRbcgzM3AwgC"
      },
      {
        "key": "manifest",
        "label": "Manifest",
        "purpose": "The CLOB the live books run on",
        "address": "HTBtzS8fV9Bw1pGRQZEZqYtu49jJLLUjU5msQWaUKfBE"
      },
      {
        "key": "oracle_adapter",
        "label": "Oracle adapter",
        "purpose": "Reads the Pyth price settlement uses",
        "address": "FMByTd4JrYycj1V7hVKHqjHnLZ5D4rwyYYscSqYiuGfz"
      },
      {
        "key": "ephemeral_spl_token",
        "label": "Ephemeral SPL",
        "purpose": "Token custody inside a live session",
        "address": "SPLxh1LVZcwhZVunT2F11mHeGVcRrU4jxvuzY4gxGy7"
      }
    ],
    "magicblock": {
      "validator": "MAS1Dt9qreoRMQ14YQuhg8UTZMMzDdKhmkZMECCzk57",
      "registeredBooks": 8,
      "trading": "verified-live",
      "settlementExit": "blocked-upstream: the public canonical ephemeral-SPL deployment does not yet accept the Magic fee-vault account required by the current public validator"
    }
  },
  "mainnet": {
    "cluster": "mainnet-beta",
    "ready": false,
    "updatedAt": null,
    "genesisHash": "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d",
    "quoteMint": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "programs": [],
    "magicblock": {
      "validator": null,
      "registeredBooks": 0,
      "trading": null,
      "settlementExit": null
    }
  }
};
