// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by web/scripts/gen-error-table.mjs from common/src/error.rs.
// Do not edit. CI regenerates this and fails on a diff.
//
// Anchor numbers `#[error_code]` variants from 6000 by declaration order, so
// each variant's position *is* its code. Inserting one anywhere but the end
// renumbers everything after it, which is why this file is checked rather
// than trusted.

export type SharedError = { code: number; name: string; msg: string };

export const SHARED_ERRORS: SharedError[] = [
  {
    "code": 6000,
    "name": "AlreadyInitialized",
    "msg": "already initialized"
  },
  {
    "code": 6001,
    "name": "NotInitialized",
    "msg": "not initialized"
  },
  {
    "code": 6002,
    "name": "Unauthorized",
    "msg": "unauthorized"
  },
  {
    "code": 6003,
    "name": "InvalidAmount",
    "msg": "amount must be positive"
  },
  {
    "code": 6004,
    "name": "AmountTooSmall",
    "msg": "amount below the series minimum"
  },
  {
    "code": 6005,
    "name": "InvalidStrike",
    "msg": "strike must be positive"
  },
  {
    "code": 6006,
    "name": "InvalidMaturity",
    "msg": "maturity must be in the future"
  },
  {
    "code": 6007,
    "name": "InvalidOracle",
    "msg": "oracle is not approved for this series"
  },
  {
    "code": 6008,
    "name": "InvalidCollateral",
    "msg": "collateral mint is not accepted"
  },
  {
    "code": 6009,
    "name": "SeriesClosed",
    "msg": "series is closed for this operation"
  },
  {
    "code": 6010,
    "name": "SeriesPaused",
    "msg": "series splits are paused"
  },
  {
    "code": 6011,
    "name": "SeriesNotMatured",
    "msg": "series has not reached maturity"
  },
  {
    "code": 6012,
    "name": "SettlementTooEarly",
    "msg": "settlement delay has not elapsed"
  },
  {
    "code": 6013,
    "name": "AlreadySettled",
    "msg": "series is already settled"
  },
  {
    "code": 6014,
    "name": "NotSettled",
    "msg": "series is not settled yet"
  },
  {
    "code": 6015,
    "name": "OraclePriceInvalid",
    "msg": "oracle price is invalid"
  },
  {
    "code": 6016,
    "name": "OraclePriceStale",
    "msg": "oracle price is stale"
  },
  {
    "code": 6017,
    "name": "OraclePairInvalid",
    "msg": "oracle reports the wrong pair"
  },
  {
    "code": 6018,
    "name": "OracleDecimalsInvalid",
    "msg": "oracle decimals are out of range"
  },
  {
    "code": 6019,
    "name": "SupplyMismatch",
    "msg": "P and N supplies do not match"
  },
  {
    "code": 6020,
    "name": "InsufficientCollateral",
    "msg": "vault holds less collateral than outstanding claims"
  },
  {
    "code": 6021,
    "name": "MathOverflow",
    "msg": "arithmetic overflow"
  },
  {
    "code": 6022,
    "name": "MathUnderflow",
    "msg": "arithmetic underflow"
  },
  {
    "code": 6023,
    "name": "DivisionByZero",
    "msg": "division by zero"
  },
  {
    "code": 6024,
    "name": "DustSweepTooEarly",
    "msg": "dust sweep requires both supplies to be zero"
  },
  {
    "code": 6025,
    "name": "InvalidDecimals",
    "msg": "decimals out of range"
  },
  {
    "code": 6026,
    "name": "InvalidParams",
    "msg": "invalid parameters"
  },
  {
    "code": 6027,
    "name": "CreationPaused",
    "msg": "series creation is paused"
  },
  {
    "code": 6028,
    "name": "SeriesExists",
    "msg": "series already exists"
  },
  {
    "code": 6029,
    "name": "SeriesNotFound",
    "msg": "series not found"
  },
  {
    "code": 6030,
    "name": "InsufficientBalance",
    "msg": "insufficient balance"
  },
  {
    "code": 6031,
    "name": "AllowanceExpired",
    "msg": "allowance expired"
  },
  {
    "code": 6032,
    "name": "MultiplierInvalid",
    "msg": "scaled UI amount multiplier is zero or unreadable"
  },
  {
    "code": 6033,
    "name": "MultiplierChangeScheduled",
    "msg": "a multiplier change is scheduled to land before maturity"
  },
  {
    "code": 6034,
    "name": "MarketClosed",
    "msg": "quote was printed outside the series' settlement window"
  },
  {
    "code": 6035,
    "name": "FeedMismatch",
    "msg": "oracle feed identity does not match the series config"
  },
  {
    "code": 6036,
    "name": "CollateralDecimalsMismatch",
    "msg": "collateral mint decimals do not match the series config"
  }
];

// `market` declares its own `#[error_code]` enum, so Anchor *does* emit an
// IDL table for it -- and its codes start at 6000 too, which means they
// collide with the shared ones. Which table applies depends on which program
// threw. Copied here so nothing has to import JSON, which needs an import
// attribute under Node's ESM loader and none under the bundler.
export const MARKET_ERRORS: SharedError[] = [
  {
    "code": 6000,
    "name": "InvalidAmount",
    "msg": "amount must be positive"
  },
  {
    "code": 6001,
    "name": "InvalidPrice",
    "msg": "price must be positive"
  },
  {
    "code": 6002,
    "name": "BookFull",
    "msg": "book is full"
  },
  {
    "code": 6003,
    "name": "NoSlot",
    "msg": "no free trader slot"
  },
  {
    "code": 6004,
    "name": "UnknownTrader",
    "msg": "trader has no slot in this book"
  },
  {
    "code": 6005,
    "name": "InsufficientBalance",
    "msg": "insufficient free balance"
  },
  {
    "code": 6006,
    "name": "OrderNotFound",
    "msg": "order not found"
  },
  {
    "code": 6007,
    "name": "NotOrderOwner",
    "msg": "not the owner of this order"
  },
  {
    "code": 6008,
    "name": "SelfFill",
    "msg": "an order cannot fill itself"
  },
  {
    "code": 6009,
    "name": "MathOverflow",
    "msg": "arithmetic overflow"
  },
  {
    "code": 6010,
    "name": "MarketClosed",
    "msg": "the series has matured; P and N are claims now, not instruments"
  }
];
