import { BN } from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";

import {
  FACTORY_PROGRAM,
  MARKET_PROGRAM,
  ORACLE_ADAPTER_PROGRAM,
  SERIES_PROGRAM,
} from "./program-addresses";

/**
 * Program ids, read from the IDLs rather than transcribed.
 *
 * These were four hardcoded literals, and all four pointed at an older
 * deployment: `factory` at `8YFvHCLy…` rather than `CRBW3Et1…`, and
 * `oracle_adapter` at `AZnVLRAs…`, which is the *Quasar variant's*
 * `declare_id!`. Both deployments are live on devnet, so nothing errored --
 * `factoryPda()` simply resolved against the wrong program, found a real
 * account there, and reported an admin nobody holds. Every admin action on
 * `/create` was disabled as a result, and the walkthrough had been skipping its
 * admin tier with "this deployed factory is administered by an external
 * wallet".
 *
 * The IDLs carry `address`, they are regenerated by `make idl`, and CI fails on
 * `git diff --exit-code web/lib/idl/`. Reading them here means a redeploy
 * cannot leave this file behind again.
 */
export { FACTORY_PROGRAM, MARKET_PROGRAM, ORACLE_ADAPTER_PROGRAM, SERIES_PROGRAM };

/** Which leg a book trades. The tag is part of the book's PDA seeds. */
export const LEG = {
  P: { tag: 0, arg: { p: {} } },
  N: { tag: 1, arg: { n: {} } },
} as const;
export type LegName = keyof typeof LEG;

const enc = new TextEncoder();
const seed = (s: string) => Buffer.from(enc.encode(s));

/** Two's-complement little-endian, matching `i128::to_le_bytes` on-chain. */
export const i128le = (v: BN | number | string) =>
  new BN(v).toTwos(128).toArrayLike(Buffer, "le", 16);
export const i64le = (v: BN | number | string) =>
  new BN(v).toTwos(64).toArrayLike(Buffer, "le", 8);

/**
 * A series address.
 *
 * The creator is part of the seeds, not just the parameters. Without it
 * `(mint, strike, maturity)` would name one address protocol-wide, and since
 * creation is permissionless anyone could occupy the address the factory was
 * about to use and block the canonical series for good.
 */
export function seriesPda(
  creator: PublicKey,
  collateralMint: PublicKey,
  strike: BN | number | string,
  maturityTs: BN | number | string,
) {
  return PublicKey.findProgramAddressSync(
    [
      seed("series"),
      creator.toBuffer(),
      collateralMint.toBuffer(),
      i128le(strike),
      i64le(maturityTs),
    ],
    SERIES_PROGRAM,
  )[0];
}

export const pMintPda = (series: PublicKey) =>
  PublicKey.findProgramAddressSync([seed("p-mint"), series.toBuffer()], SERIES_PROGRAM)[0];

export const nMintPda = (series: PublicKey) =>
  PublicKey.findProgramAddressSync([seed("n-mint"), series.toBuffer()], SERIES_PROGRAM)[0];

export const settlementPda = (series: PublicKey) =>
  PublicKey.findProgramAddressSync(
    [seed("settlement"), series.toBuffer()],
    SERIES_PROGRAM,
  )[0];

export const factoryPda = () =>
  PublicKey.findProgramAddressSync([seed("factory")], FACTORY_PROGRAM)[0];

/**
 * The factory's allowlists.
 *
 * A series cannot be created against an arbitrary feed or an arbitrary mint:
 * `create_series` takes both approval PDAs as accounts, so their existence *is*
 * the permission. Approving is admin-only, which is what stops the registry
 * filling with series priced off feeds nobody vetted.
 */
export const approvedOraclePda = (feedConfig: PublicKey) =>
  PublicKey.findProgramAddressSync(
    [seed("approved-oracle"), feedConfig.toBuffer()],
    FACTORY_PROGRAM,
  )[0];

export const approvedCollateralPda = (mint: PublicKey) =>
  PublicKey.findProgramAddressSync(
    [seed("approved-collateral"), mint.toBuffer()],
    FACTORY_PROGRAM,
  )[0];

export const recordPda = (series: PublicKey) =>
  PublicKey.findProgramAddressSync([seed("record"), series.toBuffer()], FACTORY_PROGRAM)[0];

/**
 * The config pinning one feed's identity.
 *
 * Seeded on the feed id, not on the price account. The account is rotatable by
 * the admin and the feed id is not — that asymmetry is the point of the config,
 * and seeding on the rotatable half would undo it.
 */
export const feedConfigPda = (feedId: Uint8Array) =>
  PublicKey.findProgramAddressSync(
    [seed("feed-config"), Buffer.from(feedId)],
    ORACLE_ADAPTER_PROGRAM,
  )[0];

// --- order book -----------------------------------------------------------

export const marketPda = (series: PublicKey) =>
  PublicKey.findProgramAddressSync([seed("market"), series.toBuffer()], MARKET_PROGRAM)[0];

/**
 * The book for one leg of a market.
 *
 * This is the account a rollup session delegates. While it is delegated it is
 * owned by the delegation program, so `deposit` and `withdraw` fail on L1
 * automatically — a client does not have to check, but it should explain the
 * failure rather than show a raw error.
 */
export const bookPda = (market: PublicKey, leg: LegName) =>
  PublicKey.findProgramAddressSync(
    [seed("book"), market.toBuffer(), Buffer.from([LEG[leg].tag])],
    MARKET_PROGRAM,
  )[0];
